name: Build iOS App

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make build script executable and build
        run: |
          chmod +x iOS/build_ios.sh
          cd iOS
          ./build_ios.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoonlightHMD-iOS-IPA
          path: iOS/build/MoonlightHMD.ipa